import GlassPane from "@/components/GlassPane";
import '@/styles/global.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {children}
        </GlassPane>
      </body>
    </html>
  );
}
